version: "2"

linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  goimports:
    local-prefixes: github.com/cylonchau/hermes
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false
  sloglint:
    no-mixed-args: true
    kv-only: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - ineffassign
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - revive
    - sloglint
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  exclusions:
    paths:
      - vendor

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
  tests: true
